FROM openjdk:8
ADD target/service-authentification-0.0.1-SNAPSHOT.jar service-authentification-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "/service-authentification-0.0.1-SNAPSHOT.jar"]
EXPOSE 9001